package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-05T09:13:58.194-03:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IDesconto")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IDesconto {

    @WebMethod(operationName = "ObterDesconto", action = "urn:DescontoIntf-IDesconto#ObterDesconto")
    @WebResult(name = "return", targetNamespace = "http://tempuri.org/", partName = "return")
    public java.lang.String obterDesconto(

        @WebParam(partName = "Cupom", name = "Cupom")
        java.lang.String cupom
    );
}
