package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-10-04T14:51:13.603-03:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "IDescontoservice",
                  wsdlLocation = "file:/C:/Users/alvaro.mendes/Desktop/Projeto%20Speedy/calculoSeguro/src/main/resources/wsdl/cupom.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class IDescontoservice extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "IDescontoservice");
    public final static QName IDescontoPort = new QName("http://tempuri.org/", "IDescontoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/alvaro.mendes/Desktop/Projeto%20Speedy/calculoSeguro/src/main/resources/wsdl/cupom.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IDescontoservice.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/alvaro.mendes/Desktop/Projeto%20Speedy/calculoSeguro/src/main/resources/wsdl/cupom.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IDescontoservice(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IDescontoservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDescontoservice() {
        super(WSDL_LOCATION, SERVICE);
    }

    public IDescontoservice(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IDescontoservice(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IDescontoservice(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDesconto
     */
    @WebEndpoint(name = "IDescontoPort")
    public IDesconto getIDescontoPort() {
        return super.getPort(IDescontoPort, IDesconto.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDesconto
     */
    @WebEndpoint(name = "IDescontoPort")
    public IDesconto getIDescontoPort(WebServiceFeature... features) {
        return super.getPort(IDescontoPort, IDesconto.class, features);
    }

}
